### PR TITLE
Change `contentId` to `content_id`

### PR DESCRIPTION
**Pull request by taktran**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:

Updated docs to match the API

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=651) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=651) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=651) it.</sub>

**Comment by taktran** [comment]
Haven't done everything on the checklist yet, but it's a very simple change. Can do it if need be.

`contentId` didn't work for `@sendgrid/mail` v6.1.4, but `content_id` did as per the spec https://sendgrid.com/docs/API_Reference/api_v3.html

Maybe you want to change the nodejs API though.

**Comment by thinkingserious** [comment]
Thanks @taktran!

This is now on our backlog for review.

**Comment by thinkingserious** [comment]
Thanks for taking the time to review @massm90s.

**Comment by thinkingserious** [comment]
Hello @taktran,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
