### PR TITLE
fixes #507 as assigned to me in #332

### LINKED ISSUE #332: cant understand how to use code workshop sample
#### Issue Summary

Hi, i am just starting learning back end, know a bit of Node and Express and Heroku, but i was not able to even start the server, because i dont know were used and what command should i use . 

I have found the code workshop for Node, but didnt knew what to do with the code.Maybe it's too complicated for a low level like me, i dont know.

So this is not a bug, but rather i am asking if you can make an step by step tutorial on where to put the code and how to start the server for an simple example like sending an mail from my email.

If you could build it using the heroku getting started  project (https://github.com/heroku/node-js-getting-started.git) would be so much easy for us newbies.

Thank you, bye bye.
- sendgrid-nodejs Version: master (latest commit: [commit number])
- Node.js Version: 4.1.2

### LINKED ISSUE #507: SendGrid Event Webhook consumer
The SendGrid event webhook will send email events to a URL of your choosing. Add functionality that will consume event webhook events posted 
to your server by SendGrid. Documentation: https://sendgrid.com/docs/API_Reference/Webhooks/event.html

### PR DESCRIPTION
**Pull request by itaditya**
@mbernier edit
Closes #507 
Closes #332

### CODE REVIEW

**Comment by itaditya** [comment]
@mbernier, please review it.

**Comment by mbernier** [comment]
HOLY ... This is awesome!! Thank you so much for doing this!!

**Comment by itaditya** [comment]
Hi @mbernier could you please take a look at this

**Comment by thinkingserious** [comment]
Hello @itaditya,

I will be reviewing this one once it bubbles up to the top of our backlog. My apologies on the long delay.

With Best Regards,

Elmer

**Comment by itaditya** [comment]
@thinkingserious no problem.

**Comment by thinkingserious** [comment]
Hello @itaditya,

I have begun reviewing this PR and I need a bit of help to speed the process:

1. Could you please create a quick demo of what the final solution looks like in practice? Maybe using Jing or something similar.
2. Please write up a section in the README that describes what this app does and how you would use it in practice.

Thank you!

With Best Regards,

Elmer

**Comment by itaditya** [comment]
@thinkingserious I'll try to get it done this week. Glad to hear the news :smile:

**Comment by thinkingserious** [comment]
Thank you @itaditya!

**Comment by childish-sambino** [comment]
Closing due to inactivity. Please ping here if work is to continue.

**Pull request closed without merging**
