### PR TITLE
Add void return type to void methods

### PR DESCRIPTION
**Pull request by jedborovik**
Right now this doesn't build with noImplicitAny set to true.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=630) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=630) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=630) it.</sub>

**Comment by thinkingserious** [comment]
Thanks for taking the time to review @bondz!

**Comment by bondz** [comment]
#618 already covers this BTW, this is redundant.

**Comment by thinkingserious** [comment]
Thats true @bondz, this is solved by the previous PR #619.

@jedborovik, please add your vote to PR #619 to gain it priority for merging. 

Thanks!

**Pull request closed without merging**
