### PR TITLE
Clarified how you can change the sender name

### PR DESCRIPTION
**Pull request by Sundin**
Clarified how you can change the sender name, which was not entirely obvious. Also added it to the "kitchen sink" example and fixed the link to that section in the table of contents.

# Fixes # 

### Checklist
- [ x ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x ] I have read the [Contribution Guide] and my PR follows them.
- [ x ] I updated my branch with the master branch.
- [  ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added necessary documentation about the functionality in the appropriate .md file
- [  ] I have added in line documentation to the code I modified

### Short description of what this PR does:

Some minor documentation updates.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=645) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=645) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=645) it.</sub>

**Comment by thinkingserious** [comment]
Thank you @Sundin! 

We have added this to our backlog for review.

With Best Regards,

Elmer

**Comment by Sundin** [comment]
Yep, it seems someone else fixed/changed that link during the two months since I created this PR. But my branch is now rebased with the latest changes and the link is working again!

**Comment by benstokoe** [comment]
This was very helpful! :-)

**Comment by thinkingserious** [comment]
Hello @Sundin,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
