### PR TITLE
build: fix `yarn test:files` task

### LINKED ISSUE #620: fix travis build
the travis build is failing.

https://travis-ci.org/sendgrid/sendgrid-nodejs/jobs/303605827#L3300

### PR DESCRIPTION
**Pull request by phra**
i've removed the `yarn test:files.spec` task because is not existing anymore and it's making the tests on travis fail. fixes #620

### CODE REVIEW

**Comment by phra** [comment]
i've restored the failing task, added `should` to dev deps and skipped 3 failing tests.

**Comment by ShaharHD** [comment]
Almost a month. this solves the Cl tests failing on all PRs  - any idea when this will be merged?

**Comment by thinkingserious** [comment]
@ShaharHD,

My apologies for the delay. I don't have an exact date to get this merged as we are working on a abnormally large backlog at the moment because of Hacktoberfest.

With Best Regards,

Elmer

**Comment by phra** [comment]
i think we can safely close this PR.

**Pull request closed without merging**
