### PR TITLE
Fix "method_complexity" in toJson()

### PR DESCRIPTION
**Pull request by pranavrajs**
I have refactored the method removing if statements with conditional operator

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=572) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=572) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=572) it.</sub>

**Comment by pranavrajs** [comment]
Fixes #561

**Comment by thinkingserious** [comment]
@pranavrajs

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by pranavrajs** [comment]
@thinkingserious Thanks :) Please let me know what needs to be done to get this merged.

**Comment by thinkingserious** [comment]
Hello @pranavrajs,

Sure thing! After the code review, if there are any issues, I will provide them here. Thanks!

**Comment by pranavrajs** [comment]
Guys, Is there any thing to do from my side to do merge this?

**Comment by clee** [comment]
@pranavrajs Don't think so! We just have a lot of tickets across a bunch of different projects here and only so much employee-time to wrangle all of it. We'll merge this as soon as we can!

**Comment by thinkingserious** [comment]
Hi @pranavrajs,

I'm ready to merge this now, thanks for your patience!

Could you please take a moment to fix the merge conflicts? Thank you!

With Best Regards,

Elmer

**Pull request closed without merging**
