### PR TITLE
Content is not mandatory

### LINKED ISSUE #435: Unexpected Error when trying to send transactional email
#### Issue Summary
Getting a 'Bad Request' error with the following payload.

#### Request
```
cosnt msg = {
        "to": "ian.reis@gmail.com",
        "from": "invitations@paycheck.fyi",
        "subject": "Support Pay Transparency at PayCheck",
        "templateId": "24ae3147-4faa-4380-8613-c5be144f4542",
        "customArgs": {
            "ally_id": "cj6zlh7yd000001qir4r5suuk"
        }
};
sgMail.send(msg)
```
#### Response

```
{
        "message": "Bad Request",
        "code": 400,
        "response": {
            "headers": {
                "server": "nginx",
                "date": "Wed, 30 Aug 2017 22:30:41 GMT",
                "content-type": "application/json",
                "content-length": "365",
                "connection": "close",
                "access-control-allow-origin": "https://sendgrid.api-docs.io",
                "access-control-allow-methods": "POST",
                "access-control-allow-headers": "Authorization, Content-Type, On-behalf-of, x-sg-elas-acl",
                "access-control-max-age": "600",
                "x-no-cors-reason": "https://sendgrid.com/docs/Classroom/Basics/API/cors.html"
            },
            "body": {
                "errors": [
                    {
                        "message": "Unless a valid template_id is provided, the content parameter is required. There must be at least one defined content block. We typically suggest both text/plain and text/html blocks are included, but only one block is required.",
                        "field": "content",
                        "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content"
                    }
                ]
            }
        }
    }
```
### Notes
In the documentation it says `templateId` but in the error message it says `template_id`. I've tried both and received the same error message. I attached a screenshot of my template screen as a sanity check to make sure I have it configured correctly in sendgrid.

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 6.10.3
* Running in an AWS Lambda function

screen shot 2017-08-30 at 6 43 57 pm

### PR DESCRIPTION
**Pull request by adamreisnz**
FIxes #435

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @adamreisnz,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by adamreisnz** [comment]
Is that an auto reply whenever a PR gets merged? 🤔

**Comment by thinkingserious** [comment]
Indeed. I need to make a better one for those that are as prolific as you :)

**Comment by adamreisnz** [comment]
😆

**Pull request merged**
