### PR TITLE
improve the readme and add service and namspaces file

### PR DESCRIPTION
**Pull request by inyee786**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- add nodemon package for running the server continuously
- add k8s namespace file
- Put deployment and service in tow different file
- Rename the yml to yaml
- Improve readme for running nodejs in local and run the application in minikube

Signed-off-by: inyee786 <intakhab.cusat@gmail.com>

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @inyee786,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hi @inyee786,

Thank you for the contribution! 

Can you please repair the merge conflicts?

With Best Regards,

Elmer

**Comment by aroach** [comment]
This has some nice additions, however it will also conflict with my PR that combines inbound parse and event webhook.  See #804 

So, if possible, @inyee786 could you update your changes based on #804?

**Comment by inyee786** [comment]
Sure

**Comment by thinkingserious** [comment]
Hello @inyee786,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 8 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by childish-sambino** [comment]
Closing until PR comments have been addressed.

**Pull request closed without merging**
