### PR TITLE
Change to param to use Web API instead of X-SMTPAPI header

### PR DESCRIPTION
**Pull request by tushdante**
Hey @eddiezane . Here's the changes I've made. Would love it if you could give it a quick look through for me.

Thanks!

### CODE REVIEW

**Comment by tushdante** [comment]
Also, closes #162

**Comment by eddiezane** [comment]
The first failing test, `should not have multiple TOs if as an array but also set on smtpapi via addTo`, can probably be removed. No idea what that was even testing for.

The second one, `should have a to address if there is no to but there is an smtpapi to` was needed because the request would fail if there was no `to` param provided - even when using smtpapi. We would set it to the `from` in that case. Can probably be reworked and reworded for the new way.

**Comment by tushdante** [comment]
So basically for the second one, `expect(JSON.parse(format['x-smtpapi']).to).to.not.be.empty;` needs to be removed cause we're not setting any `to` fields in the `smtpapi` headers anyway.

**Comment by tushdante** [comment]
@thinkingserious so it looks like the build is failing on node v0.8 due to issues with either travis or node itself. i'm not sure how to procceed

**Comment by thinkingserious** [comment]
Found the answer here: https://github.com/npm/npm/issues/9668 :/

**Comment by tushdante** [comment]
Sweet! Thanks @thinkingserious Gotta finish up a few more tests and it should be ready for a code review

**Comment by elbuo8** [comment]
This PR looked great guys. What I didn't see was, if the user only uses `smtpapi` recipients, no fake `Web API` recipient is set. That would cause it to break and not send the email. (This might have been fixed, but most libs have workarounds for that). Make sure you test sending just using `smtpapi` on dev env.

**Comment by thinkingserious** [comment]
Thanks for the extra set of eyes @elbuo8. Testing now :)

**Comment by thinkingserious** [comment]
Successfully tested using:

```
var sg = require('./lib/sendgrid')('<my_api_key>');
var email = new sg.Email();
email.addSmtpapiTo('elmer.thomas@gmail.com');
email.subject = 'Testing via SMTPAPI only';
email.from = 'dx@sendgrid.com';
email.text = 'Testing';
sg.send(email, function(err, json) {
  if (err) console.error(err);
  console.log(json);
});
```

**Comment by elbuo8** [comment]
I missed this https://github.com/sendgrid/sendgrid-nodejs/blob/master/lib/email.js#L225

That's the hack that makes it work. Awesomeness :+1:

**Pull request merged**
