### PR TITLE
Fix bug #310

### PR DESCRIPTION
**Pull request by shkabo**
Added UTF-8 encoding for emails

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @shkabo,

Thanks for the pull request!

Could you please sign our CLA, so we can get this merged? https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla

Thanks!

**Comment by thinkingserious** [comment]
@shkabo,

I could not reproduce the error, please see: https://github.com/sendgrid/sendgrid-nodejs/issues/310

Could you please add unit tests that demonstrate failure if your code was not included? Thanks!

**Comment by shkabo** [comment]
@thinkingserious you can close th

**Comment by thinkingserious** [comment]
@shkabo Thanks!

**Pull request closed without merging**
