### PR TITLE
Update documentation with new Git workflow

### LINKED ISSUE #799: Document new Git workflow in CHANGELOG.md
#### Issue Summary

We want to update our git workflow to function more like [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). We need to update the CONTRIBUTING.md file and PULL_REQUEST_TEMPLATE to direct contributors to fork/branch off the `development` branch and to merge their PRs with the `development` branch. Once this issue is complete, we will be creating the `development` branch and making that branch the default. This is part of a larger strategy to execute releases for this SDK on a predictable cadence.

#### Acceptance Criteria

* Update CONTRIBUTING.md documentation, explaining the process of forking and branching off the `development` branch and submitting PRs agains the `development` branch.
* Update PULL_REQUEST_TEMPLATE with the same addition to the CONTRIBUTING.md documentation.

### PR DESCRIPTION
**Pull request by tony-ho**
# Fixes # 
Fixes #799

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Update CONTRIBUTING.md documentation, explaining the process of forking and branching off the development branch and submitting PRs against the development branch.
- Update PULL_REQUEST_TEMPLATE with the same addition to the CONTRIBUTING.md documentation.
- Remove duplicate content PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @tony-ho,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @tony-ho,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 2 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by thinkingserious** [comment]
Hi @tony-ho,

Please resolve the merge conflict and I'll get this one merged. Thank you!

With Best Regards,

Elmer

**Comment by tony-ho** [comment]
@thinkingserious Merge conflicts have been resolved.

Note the PR build fails due to the build failures on master. I've resolved these in #824.

**Comment by thinkingserious** [comment]
Hello @tony-ho,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
