### PR TITLE
fix error

### PR DESCRIPTION
**Pull request by ugurnc**
node_modules/@sendgrid/helpers/classes/email-address.d.ts(11,3): error TS7010: 'fromData', which lacks return-type annotation, implicitly has an 'any' return type.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=479) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=479) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=479) it.</sub>

**Comment by thinkingserious** [comment]
Hi @ugurnc,

I'm not sure if you meant to merge this back into our repo. If so, there are a few commits here where we need signed CLAs. Thanks!

With Best Regards,

Elmer

**Comment by mbernier** [comment]
@ugurnc, @kirillgroshkov, @cimdalli

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by thinkingserious** [comment]
Hi!

It looks like we need a couple of things to get this merged:

1. A [signed CLA](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=479) by @kirillgroshkov
2. A fix of the merge conflicts listed above

Thanks!

With Best Regards,

Elmer

**Pull request closed without merging**
