### PR TITLE
[contact-importer] Update to support @sendgrid/client v6.X

### LINKED ISSUE #427: Update contact-importer to support v6.X
#### Issue Summary

The current version of [contact-importer](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/contact-importer) needs to be updated to leverage the new [@sendgrid/client](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/client).

#### Acceptance Criteria

- Passing Tests
- README.md

### PR DESCRIPTION
**Pull request by aslafy-z**
Closes #427 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Upgrade contact-importer to use @sendgrid/client v6.X

### CODE REVIEW

**Comment by aslafy-z** [comment]
Still need to upgrade Bottleneck to v2. https://github.com/SGrondin/bottleneck#upgrading-to-v2

**Comment by thinkingserious** [comment]
Hello @aslafy-z,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @aslafy-z,

Is this still WIP?

Thanks!

With Best Regards,

Elmer

**Comment by aslafy-z** [comment]
Bottleneck could be upgraded in another PR. It's not WIP anymore @thinkingserious.

**Pull request merged**
