### PR TITLE
Allows hiding warnings

### PR DESCRIPTION
**Pull request by albertor24**
# Fixes # 

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the development branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Description
-  Allows hiding warnings by using a "hideWarnings" parameter in the Mail class.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @albertor24,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by vieira** [comment]
Hello, any idea when this will land on a release? We have our logs full of these warnings...

**Comment by Rowern** [comment]
@thinkingserious Any estimation for when this will get released ? This a pretty annoying thing, it breaks our log processor as it's not using our logger but a "dirty" `console.warn`...

**Comment by vieira** [comment]
Hello @thinkingserious 

Any idea when this will land? We have been waiting for months now having to manually set the `sendgrid-helpers` version to 6.3.0 in `yarn.lock` to avoid dirty logs!

Is there anything that still needs to be done before this can be released?

**Comment by sergiuds** [comment]
Is this merged yet? It fills my logs with error and triggers my monitoring alerts :(

**Comment by andynunes** [comment]
Bah, I just spent a while trying to figure out why the `hideWarnings` options was not available in the latest version from npm. Bump for a soon release please! Thanks!

**Comment by childish-sambino** [comment]
Releasing soon ...

**Comment by Wtrapp** [comment]
hey @childish-sambino @thinkingserious is this fixed ?

**Comment by childish-sambino** [comment]
@Wtrapp Yes.

**Comment by Wtrapp** [comment]
What version? @childish-sambino I'm using "@sendgrid/mail": "^7.0.0" with nodeJS and still getting the errors/warnings. 

`Content with characters ', " or & may need to be escaped with three brackets
{{{ content }}}
See https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/ for more information.`

Thanks for the quick response.

**Comment by childish-sambino** [comment]
Should've been in `6.5.0`. Are you passing the `hideWarnings` property? https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/hide-warnings.md

**Comment by Wtrapp** [comment]
Of course I was not passing that property otherwise it would have been working perfectly. 

Easy fix. Working great now. THANK YOU!!!

**Pull request merged**
