### PR TITLE
fix: update MailService constructor property definition in TypeScript declaration

### PR DESCRIPTION
**Pull request by dhritzkiv**
Before, `{MailService: MailService}` suggested an instance of `MailService` was being passed. Changing the syntax to ~~`{new(): MailService}`~~ `typeof MailService` suggests that it's a callable constructor reference available as a property

# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the development branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=921) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=921) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=921) it.</sub>

**Comment by thinkingserious** [comment]
@SPARTAN563,

Do you mind giving this one a quick look? Thanks!

**Comment by dhritzkiv** [comment]
@SPARTAN563 you're right; made the change to `typeof`

**Comment by bs85** [comment]
@thinkingserious any reason this wasn't merged? This is forcing us to use ugly hacks anywhere we need to create a new instance of that class.

**Comment by thinkingserious** [comment]
Hello @dhritzkiv,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
