### PR TITLE
PR: Update the USAGE.md with the call to list all templates.

### LINKED ISSUE #777: Update documenation for retrieving a list of all templates (dynamic & legacy)
#### Issue Summary

Please update the `USAGE.md` with the call to list all templates. 

This is the API call required: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

#### Acceptance Criteria

* The Usage.md file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

### PR DESCRIPTION
**Pull request by AllUsernamesHaveBeenTaken**
# Fixes #777 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- This PR will update the USAGES.md file's GET /templates with params.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=783) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=783) before we can accept your contribution.<br/><hr/>**Seppe Snoeck** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=783) it.</sub>

**Comment by reedsa** [comment]
Also, please sign the CLA before we merge.

**Comment by AllUsernamesHaveBeenTaken** [comment]
> Also, please sign the CLA before we merge.

I signed it though but it seems like the bot doesn't recognize my signature.

**Comment by thinkingserious** [comment]
Hello @AllUsernamesHaveBeenTaken, 

Can you please add an email to your GitHub profile and then re-sign the CLA? Thanks!

**Comment by childish-sambino** [comment]
Closing since CLA has not been signed. OP may also fill in added checkbox to description.

**Pull request closed without merging**
