### PR TITLE
Prevent secrets from sending in email

### LINKED ISSUE #496: Prevent secrets from sending in email
Add a method that will check the content of the email before sending, to make sure that specific strings or patterns are not included.

For example, SG API keys look like this: SG.[a-zA-Z0-9_].[a-zA-Z0-9\-].

So the function could take a list of regex or specific strings to compare against. If a string is found, the mail/send should throw an exception

### PR DESCRIPTION
**Pull request by spelcaster**
- Added the methods:
  - setSecretRules: user can configure a set of named rules to test the
    e-mail content;
  - filterSecrets: this method test all the e-mail content with the
    rules configured in setSecretRules, nothing is done if secretRules
    is empty, and if a rule is found in the e-mail content, then a
    exception is thrown;
- The method filterSecrets is called before the request to the API and
  should prevent sensitive data leakage;

@mbernier edit:
closes #496

### CODE REVIEW

**Comment by spelcaster** [comment]
https://github.com/sendgrid/sendgrid-nodejs/issues/496

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=502) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=502) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=502) it.</sub>

**Comment by spelcaster** [comment]
Sample file:
```js
// mail_sample.js
const sgMail = require('./packages/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

sgMail.setApiKey(process.env.SENDGRID_API_KEY);
sgMail.setSecretRules({'sendgridApiKey':/SG\.[a-zA-Z0-9_]+\.[a-zA-Z0-9-]+/});
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with SendGrid is Fun',
  text: 'SG.Xx1XX.Xx1XX-Xx1X-X1xXX-XX11X-XxX and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg);

```

Result:
```shell
node mail_sample.js 
(node:12659) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): The pattern '/SG\.[a-zA-Z0-9_]+\.[a-zA-Z0-9-]+/' identified by 'sendgridApiKey' was found in the message!
```

**Comment by spelcaster** [comment]
@clee done!. 

I've squashed one of the commits and changed how my variables were declared, I'm using `const` and `let` now

**Comment by clee** [comment]
@spelcaster Awesome! Thanks for taking care of this so quickly. I’ll check with the rest of the team to see how soon we can get this merged.

**Comment by spelcaster** [comment]
@clee, Is there any change to be done here yet?

**Comment by thinkingserious** [comment]
Hi @spelcaster,

Everything is good on your end. This is now on our backlog for merge.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @spelcaster,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
