### PR TITLE
[WIP] Run prism for tests

### PR DESCRIPTION
**Pull request by MikeRalphson**
Refs #316 

I wanted to implement this as I thought I should have working tests before looking at any other issues.

Maybe @tsriram and I could collaborate on this?

Current limitations; does not work on Node 0.10 or 0.12, which are both at or near end-of-life... (as a bonus, it does pass on Node 6, as well as 4 and iojs). 

Please let me know if I'm working along the right lines.

### CODE REVIEW

**Comment by thinkingserious** [comment]
@MikeRalphson,

I'm not opposed to a collaboration, but it looks like @tsriram is out until the 23rd.

In the mean time, we will need a [signed CLA](https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla) in order to merge your changes. Could you please take care of that for us?

**Comment by MikeRalphson** [comment]
@thinkingserious CLA DocuSign'ed and sent.

**Comment by MikeRalphson** [comment]
Now passing on Node 0.12 - [PR](https://github.com/jochemstoel/nodejs-system-sleep/pull/1) submitted to `system-sleep` module, ugly temporary work-around in place for Travis builds.

@thinkingserious what would be the chance of upping the minimum-required Nodejs version to v0.11.12 ? This provides `child-process.execSync`. If not, I will look at using `async-queue`...

**Comment by thinkingserious** [comment]
Based on [this table](https://github.com/nodejs/LTS/issues/31), it looks like we need to keep support for .10 until 12/31/16.

Do you have a reference that could help us make the justification to drop support earlier?

Thanks!

**Comment by MikeRalphson** [comment]
@thinkingserious as per the table you quoted, I believe the original plan was to end LTS for Node 0.10 three months before the OpenSSL end-of-life of 31-Dec-2016, i.e. 01-Oct-2016 . This has now crept out to the [end of October](https://github.com/nodejs/LTS#readme).

**Comment by thinkingserious** [comment]
Thanks @MikeRalphson!

We will remove support on November 1 in that case.

**Comment by heitortsergent** [comment]
@MikeRalphson did you run into this error when running the tests by any chance?

```
...
Uncaught SyntaxError: Unexpected token M in JSON at position 0
      at JSON.parse (<anonymous>)
      at lib/sendgrid.js:110:42
...
```

I was testing out the changes to see if everything was working with Node.js v7. 😄

**Comment by MikeRalphson** [comment]
@heitortsergent No all tests passed on Node 0.12, 4 and 6. I will try and add Node 7 and see if the error appears for me.

**Comment by heitortsergent** [comment]
@MikeRalphson that's great!

I think the error I'm seeing might be a local problem then... Do I need to run any command(s) besides `npm install` before running `npm test`?

**Comment by MikeRalphson** [comment]
@heitortsergent You shouldn't need to, no.

Maybe try replacing the two instances of

````javascript
response.body = response.body ? JSON.parse(response.body) : response.body;
````

in lib/sendgrid.js with

````javascript
try {
    response.body = JSON.parse(response.body);
}
catch (ex) {}
````

To help diagnose the issue?

**Comment by thinkingserious** [comment]
Hi @MikeRalphson,

Once the conflicts are merged, is this one ready to go?

With Best Regards,

Elmer

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=325) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=325) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: MikeRalphson<br/>:x: thinkingserious<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=325) it.</sub>

**Comment by thinkingserious** [comment]
Hello @MikeRalphson,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
