### PR TITLE
Expose Client and MailService classes

### LINKED ISSUE #649: No clear usage path for multiple keys
Hi,

While I love SendGrid as a service, I'm starting to despise SendGrid's Nodejs implementation. It works great for a single API Key, but I'm venturing into the domain of requiring support for multiple API Keys.

Your repo is very confusing. Installing `npm install sendgrid`, brings us to this repository, which has an issue that was resolved (#275) that somehow gives us this ability, but every example I find is using `@sendgrid/email`. There isn't a clear path for me to provide my own client to the email instance, installing this repo didn't install the email class either.

Thanks for any help.

### PR DESCRIPTION
**Pull request by adamreisnz**
# Fixes #649 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] ~~~I have added tests that prove my fix is effective or that my feature works~~~
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
This PR exposes the `Client` and `MailService` classes via their default module exports allowing end users to manually instantiate client or mailer instances, so that multiple API keys or different settings can be used without affecting the global singleton client and mailer instances.

### Example usage

Mailer:
```js
//Import mail service class
const {MailService} = require('@sendgrid/mail');

//Instantiate mailers
const sgMail1 = new MailService();
const sgMail2 = new MailService();

//Set different API keys
sgMail1.setApiKey('KEY1');
sgMail2.setApiKey('KEY2');
```

Client:
```js
//Import client class
const {Client} = require('@sendgrid/client');

//Instantiate clients
const sgClient1 = new Client();
const sgClient2 = new Client();

//Set different API keys
sgClient1.setApiKey('KEY1');
sgClient2.setApiKey('KEY2');
```

### Notes
- Backwards compatible as the singleton instances are still the default exports
- TypeScript definitions have *not* been updated or amended
- Documentation and use cases have been updated
- No new tests added as no new functionality was added, merely exposed the classes
- Ran tests on client and mail sub packages to verify still working ok

cc @thinkingserious @tflanagan

### CODE REVIEW

**Comment by adamreisnz** [comment]
@thinkingserious I've updated the license year as well to fix the failing build. Maybe put that check in first, so that the Travis build fails faster without having to run the rest of the tests first before it finds out something trivial like that fails?

**Comment by thinkingserious** [comment]
Hi @adamreisnz,

LGTM

With regards to the tests, I agree. 

For the remaining failing test, I believe [this](https://github.com/sendgrid/sendgrid-nodejs/pull/605) should fix it.

**Comment by thinkingserious** [comment]
Hello @adamreisnz,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by J-Gonzalez** [comment]
Is this documented anywhere other than here? We had to dig for this one as we wanted different emails to go out from different subusers on our account (transactional vs marketing etc). This merged PR def does the job, it's just not documented anywhere from what I could find (and I always worry that non-documented items are the first to get changed without notice).

**Comment by adamreisnz** [comment]
It is documented I think:

https://github.com/sendgrid/sendgrid-nodejs/pull/650/files#diff-16de12bd15ad576dabb90898a018f770R85

**Comment by J-Gonzalez** [comment]
Ah yea - It seems it's in the client README file, but not in the Mail README, but used to also be in the Mail USECASES file, but that since has been edited to link [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/README.md#email-use-cases) and no longer has that info.

**Comment by thinkingserious** [comment]
Thanks for the heads up @J-Gonzalez, I've filed an issue for a fix.

Thanks for helping out @adamreisnz!

**Pull request merged**
