### PR TITLE
feat: Add method chaining in mail-service.js

### LINKED ISSUE #682: Allow method chaining in @sendgrid/mail
#### Issue Summary

Very minor, but it would be nice to allow method chaining in the `MailService` of `@sendgrid/mail` so that setting the API key could be handled on one line:

```js
const mailer = require('@sendgrid/mail').setApiKey(process.env.SENDGRID_API_KEY);

// vs

const mailer = require('@sendgrid/mail');

mailer.setApiKey(process.env.SENDGRID_API_KEY);
```

This is all it would require as far as I can tell:
```js
class MailService {
  // ...

  setClient(client) {
    this.client = client;

    return this; // TODO (optional, but good for consistency)
  }

  setApiKey(apiKey) {
    this.client.setApiKey(apiKey);

    return this; // TODO
  }

  setSubstitutionWrappers(left, right) {
    // ...

    return this; // TODO (optional, but good for consistency)
  }

  // ...
}
```

(It looks like this pattern is used here in `@sendgrid/client` https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/src/classes/client.js#L53-L67 as well.)

#### Steps to Reproduce

1. Install `@sendgrid/mail`
2. Set the API key

#### Technical details:

* sendgrid-nodejs version ^6.2.1

### PR DESCRIPTION
**Pull request by hjmsw**
Fixes #682 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
### Short description of what this PR does:

Adds method chaining to mail-service.js, as demonstrated in #682

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=712) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=712) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=712) it.</sub>

**Comment by thinkingserious** [comment]
Thanks @hjmsw!

This has been added to our backlog for a code review. We are a bit backlogged, so it may be some time, but we greatly appreciate your contribution!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @hjmsw,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @hjmsw,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Review by childish-sambino — APPROVED** [review]
LGTM!

**Pull request merged**
