### PR TITLE
Expose `client` for testing stub-ability

### PR DESCRIPTION
**Pull request by fyockm**
also ternary FTW

### CODE REVIEW

**Comment by thinkingserious** [comment]
@fyockm,

Awesome! Could you please take a moment to sign our CLA so I can merge this? https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla

Thanks!

**Comment by thinkingserious** [comment]
Hi @fyockm,

This one finally came up to the top of our queue. Could you please repair the conflicts and I'll go ahead and merge it.

To test this locally:
1. Download https://stoplight.io/prism/
2. `./prism run --mock --list --spec https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai_stoplight.json`
3. `mocha`

**Comment by thinkingserious** [comment]
@fyockm,

Just check in :)

**Comment by fyockm** [comment]
@thinkingserious I updated my branch. All tests pass locally.

#277 actually exposed the client already. So, this PR boils down to a more terse (though potentially less readable?) ternary expression around Promise. At this point, very little value added in my opinion. Feel free to merge or close.

**Comment by peteyy** [comment]
@fyockm where does #277 expose the client? Your way is much clearer and it makes stubbing a lot easier, which is currently not doable.

Could you please update this branch because right now the library is untestable without modifications.

**Comment by thinkingserious** [comment]
@adamreisnz,

Does your version solve this issue?

**Comment by adamreisnz** [comment]
Yes it does actually :)

**Comment by thinkingserious** [comment]
This issue will be resolved with: https://github.com/sendgrid/sendgrid-nodejs/pull/378

**Pull request closed without merging**
