### PR TITLE
-function removes html tags to string

### PR DESCRIPTION
**Pull request by uniOpifex**
contribution for Hacktoberfest.

#453

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=454) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=454) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=454) it.</sub>

**Comment by thinkingserious** [comment]
This looks good @uniOpifex,

Could you please add a few tests?

Thanks!

With Best Regards,

Elmer

**Comment by mbernier** [comment]
@uniOpifex

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hi @uniOpifex,

Just checking in. Will you be able to add a few tests so that we can review and merge?

With Best Regards,

Elmer

**Pull request merged**
