### PR TITLE
Easy permissions class

### PR DESCRIPTION
**Pull request by hicks2evan**
I think I fixed the issue with my conflicting local user account! This PR has a class that can be used to easily generate user permissions arrays. @thinkingserious thanks so much!

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=569) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=569) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: hicks2evan<br/>:x: Evan Hicks<br/><hr/>**Evan Hicks, hicks2evan** seem not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=569) it.</sub>

**Comment by hicks2evan** [comment]
Shoot, it looks like it's viewing that old local username as a contributor, is there a workaround for this?

**Comment by thinkingserious** [comment]
Hi @hicks2evan,

You would need to remove the commits from that user. Probably easier to just submit a new PR.

With Best Regards,

Elmer

**Comment by clee** [comment]
@hicks2evan Just a heads-up: you can in fact fix your local commit history using 'git rebase --interactive'! If you would like some help with this, you can find me on IRC (irc.freenode.net) as 'clee', and I'd be happy to walk you through it. Since the commit history issue seems to be the only thing standing in the way of merging this, it'd be great if we could get that fixed up!

**Comment by thinkingserious** [comment]
HI @hicks2evan,

It looks like the issue is that, besides the last 3, your commits are attributed to a non-GitHub account. It might be easier to just close this PR and create a new one which is authored solely by your @hicks2evan account.

Thanks!

With Best Regards,

Elmer

**Pull request closed without merging**
