### PR TITLE
Added CODE_OF_CONDUCT

### PR DESCRIPTION
**Pull request by arguiot**
There was missing a CODE OF CONDUCT in the project, so I added one using the [weallbehave](https://github.com/WeAllJS/weallbehave) generator. The CODE OF CONDUCT is a community standard that establishes rules of how you should behave with the project.

Hope it helps 😊.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=451) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=451) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=451) it.</sub>

**Comment by mbernier** [comment]
Hey @arguiot!! Thank you so much for the nudge here! We have wanted to add a code of conduct to each of our repos and you PR was exactly what we needed. 

Our legal team just wrote our [official Code of Conduct](https://github.com/sendgrid/docs/pull/3048) and then made a PR to our docs!! 
If an enterprising github contributor, such as yourself, was to go and copy it to our API libraries... that would be pretty sweet. 

Here's the PR with the content already in markdown! https://github.com/sendgrid/docs/pull/3048  -- Would you be up for changing your PR to use this content? 

I am going to add an issue to each library (except this one) for this.

**Comment by arguiot** [comment]
@mbernier Done, I copied the code ;)

**Comment by mbernier** [comment]
Fantastic work, thank you!!

**Comment by thinkingserious** [comment]
Hello @arguiot,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@arguiot 
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
