### PR TITLE
refactored specs fixes #552

### LINKED ISSUE #552: Fix "file_lines" issue in packages/helpers/classes/personalization.spec.js
File `personalization.spec.js` has 641 lines of code (exceeds 250 allowed). Consider refactoring.

Move each example out to its own file and add a markdown that links to each example.

https://codeclimate.com/github/sendgrid/sendgrid-nodejs/packages/helpers/classes/personalization.spec.js#issue_59f39f42b5ec1a000100006c

### PR DESCRIPTION
**Pull request by t2013anurag**
This PR fixes #552

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=558) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=558) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=558) it.</sub>

**Comment by t2013anurag** [comment]
@thinkingserious - can you review it?

**Comment by t2013anurag** [comment]
@thinkingserious - code climate rating for this [spec](https://codeclimate.com/github/sendgrid/sendgrid-nodejs/packages/helpers/classes/personalization_specs/to-json.spec.js?to_sha=069d226952dfa21ff8c16778f669bfee9aa98fd5) is poor due to some duplicated code found in other specs such as cc, bcc follow same format.

**Comment by mbernier** [comment]
This is so cool!! Thank you!

**Comment by thinkingserious** [comment]
Hello @t2013anurag,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
