### PR TITLE
Enhacement - ES6-ify Inbound Mail Parser

### PR DESCRIPTION
**Pull request by rafaelverger**
refs #533

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=544) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=544) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=544) it.</sub>

**Comment by rafaelverger** [comment]
@mbernier could u check this?

**Comment by mbernier** [comment]
There are a couple new merge issues - can you please resolve these? I am not confident enough with node and ES6 to be able to merge this myself.

**Comment by rafaelverger** [comment]
@mbernier , sure thing... I'm checking it right now

**Comment by rafaelverger** [comment]
@mbernier all set :)

**Comment by thinkingserious** [comment]
Hello @rafaelverger,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
