### PR TITLE
Added unittest to check for specific repo files

### PR DESCRIPTION
**Pull request by mptap**
Fixes https://github.com/sendgrid/sendgrid-nodejs/issues/565

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=568) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=568) before we can accept your contribution.<br/><hr/>**Manjiri Tapaswi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=568) it.</sub>

**Comment by mbernier** [comment]
@mptap 
I think I might be blind - are you seeing the tests running here? https://travis-ci.org/sendgrid/sendgrid-nodejs/jobs/294203681

**Comment by mptap** [comment]
@mbernier: Done

**Comment by mbernier** [comment]
Looks great, thank you!

**Comment by thinkingserious** [comment]
Hello @mptap,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
