### PR TITLE
added modularization for FromData

### PR DESCRIPTION
**Pull request by SidduH**
Added few formatting and modulated the formData method

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=559) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=559) before we can accept your contribution.<br/><hr/>**Siddu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=559) it.</sub>

**Comment by mbernier** [comment]
Hey @SidduH, can you please sign the CLA? We cannot merge your code unless you do. Thank you.

**Comment by mbernier** [comment]
Annnndd... I am out of my depth here.  @thinkingserious please help!

**Comment by childish-sambino** [comment]
Closing due to inactivity. Please ping here if work is to continue.

**Pull request closed without merging**
