### PR TITLE
fix: update definitions for tsc 2.6, fixes #618

### LINKED ISSUE #618: typescript definitions errors
#### Issue Summary

This package prevents typescript to work correctly due to problems with typescript definitions.

```
node_modules/@sendgrid/client/src/client.d.ts(37,10): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.
node_modules/@sendgrid/helpers/classes/email-address.d.ts(11,3): error TS7010: 'fromData', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/@sendgrid/helpers/classes/email-address.d.ts(16,3): error TS7010: 'setName', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/@sendgrid/helpers/classes/email-address.d.ts(21,3): error TS7010: 'setEmail', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/@sendgrid/mail/src/mail.d.ts(33,10): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.
```

#### Steps to Reproduce

1. Install latest typescript
2. Install latest @sendgrid/mail
3. Set up a strict typescript environment

#### Technical details:

* sendgrid-nodejs Version: 6.1.4
* Node.js Version: 9.1
* TypeScript: 2.6.1

### PR DESCRIPTION
**Pull request by phra**
i've updated the definitions files to support typescript 2.6. fixes #618

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=619) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=619) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=619) it.</sub>

**Comment by phra** [comment]
i'm still depending on `quickfix` in order to be able to deploy my project to production.. can you please merge this?

**Comment by thinkingserious** [comment]
@SPARTAN563,

If you have a moment, a quick review would be much appreciated. Thanks!

**Comment by SPARTAN563** [comment]
Looks perfect to me :+1:

**Comment by thinkingserious** [comment]
Awesome, this has been added to our backlog for final review and merge.

**Comment by phra** [comment]
@thinkingserious i've also sent https://github.com/sendgrid/sendgrid-nodejs/pull/621 to fix the CI, i don't know if it's still required but 11 days ago was needed to make the CI work again.

**Comment by ShaharHD** [comment]
Been almost 3 weeks now. Any ETA on getting this small fix merged?
It has not implications other than making this library usable in TS 2.6 from what I can see.

**Comment by joseSantacruz** [comment]
Hi, I also need to merge this PR to deploy to prod

**Comment by wwwy3y3** [comment]
+1 need this PR.
@thinkingserious any plan for this fix?

**Comment by thinkingserious** [comment]
Hello @ShaharHD @joseSantacruz @wwwy3y3,

This PR is on our backlog, which we are working through from oldest to newest. Our backlog is a bit overloaded because of Hacktoberfest, tub we are currently working to get caught up.

My apologies for the delay and I do appreciate your support and patience.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Thanks for taking the time to check it out @jdanyow!

**Comment by ShaharHD** [comment]
Why wasn't this included in `6.2.0`?

**Comment by phra** [comment]
hopefully i can continue to ship to production thanks to [quickfix](https://github.com/maxchehab/quickfix). :v: 

@ShaharHD @thinkingserious  this PR should be merged ASAP because doesn't have any conflicts or regressions and fixes problems with typescript 2.6, so i don't see any reason to not merge this!

**Comment by thinkingserious** [comment]
Thanks @phra!

I have this on my list to deploy today.

**Comment by thinkingserious** [comment]
Hi @phra,

Before I merge this, could you please take a look at this [recently merged PR](https://github.com/sendgrid/sendgrid-nodejs/pull/650) to see if any further TypeScript changes are necessary? Thanks!

With Best Regards,

Elmer

**Comment by SPARTAN563** [comment]
It looks like there are some changes that are necessary to align it with the newly exported module spec. Specifically, rather than simply exporting [`Client`](https://github.com/sendgrid/sendgrid-nodejs/pull/619/files#diff-b276d386efd61d0ca679143fd4966d4aR37), we should be exporting something like `Client & { Client: typeof Client }`. The same applies to the [`MailService`](https://github.com/sendgrid/sendgrid-nodejs/pull/619/files#diff-0ab4f6d710cac1c2f8b58f99841c835fR33) export.

Should be a pretty easy fix.

**Comment by phra** [comment]
i will do it later today. :+1:

**Comment by phra** [comment]
done. can you review the code? @thinkingserious @SPARTAN563

**Comment by thinkingserious** [comment]
Thanks to @phra and @SPARTAN563 for being AWESOME and getting this done so quickly! I should have this deployed no later than tomorrow.

**Comment by bunnyvishal6** [comment]
@thinkingserious  waiting for this pr to be merged. When will it be done?

**Comment by thinkingserious** [comment]
@bunnyvishal6,

I'm shooting for some time today.

**Comment by thinkingserious** [comment]
Hello @phra,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by 0x80** [comment]
Thanks for fixing this 👍  I can now set the compiler back to strict mode 😄

**Comment by thinkingserious** [comment]
Awesome, thanks for the comment @0x80!

**Comment by phra** [comment]
@hansenst at the time of committing, it was working properly. can you check it using tsc version ~2.6 ? i can eventually send another PR fixing it if it doesn't break v2.6 release or look for a solution that can work on tsc 2.6 and newer versions.

**Comment by hansenst** [comment]
Sorry @phra, I was somewhat unclear in my comment. Typescript itself is happy with the current types, but calling the `setApiKey` fails (it just gets stuck and eventually things time out).  Changing the  type definitions to `Client & { Client: typeof Client }` resolves the issue.

We're currently using TS 2.8.3.

**Pull request merged**
