### PR TITLE
[WIP] Fix spelling of substitutions in lib/helpers/mail/mail.js

### PR DESCRIPTION
**Pull request by cameronoca**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Awesome, thanks @cameronoca!

To merge this I will need a signed CLA: https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla

Thanks!

**Comment by julio-vaz** [comment]
Are you seriously ignoring a bug in your master branch(release) because of bureaucracy? This bug is affecting us and we're using a workaround that writes the content of substition inside of substitution in the object.

**Comment by thinkingserious** [comment]
Thanks for the vote @julio-vaz. Every vote or comment helps move tasks up our priority queue. 

When this one bubbles up to the top, if the CLA is still not signed, we will make the changes ourselves.

There are a few things that can continue to help this gain priority:

1. More +1's or comments
2. The CLA to this change to be signed
3. A new pull request with a signed CLA

Apologies for the delay and we will get this fixed as soon as we can.

**Comment by julio-vaz** [comment]
It's been 23 days already! What more do you guys need?

**Comment by thinkingserious** [comment]
Hi @julio-vaz,

I appreciate your frustration, we want this to be fixed 23 days ago. 

Unfortunately, we have quite a few tickets above this one that need to be fixed, all important. We are doing our best to solve them as fast as we can.

That said, I appreciate your voice as it will help us make the case to increase our resources to solve these issues faster. 

We are agile and we constantly are iterating towards improvement. We thank you once again for taking the time to express your feedback.

**Comment by thinkingserious** [comment]
I'm going to go ahead and fix this one.

**Pull request closed without merging**
