### PR TITLE
#692 multi line codes in <pre> turn to one line after mail send.

### LINKED ISSUE #692: multi line codes in <pre> turn to one line after mail send.
#### Issue Summary

I use mail to write my blog.
with markdown syntax.
```
int a = 10;
int b = 10;
int c = 10;
```
it will generate below html code:
<pre><code>int a = 10;
int b = 10;
int de = 10;
</code></pre>

then I send this html code to my blogger.
but in the post of my blog, the html change
<pre><code>int a = 10; int b = 10; int de = 10;</code></pre>
All codes are in one line, which is not my want.

Would you help me to work around for it please ?

#### Steps to Reproduce
          sgMail.setApiKey(process.env.SENDGRID_API_KEY);
          let msg = {
            to: 'errong.leng@blogger.com',
            from: 'errong.leng@gmail.com',
            subject: title,
            html: html,
          };
         sgMail.send(msg);

I confirm that html is correct and the codes are multi lines.
console.log(html)'s output is
<pre><code>int a = 10;
int b = 10;
int de = 10;
</code></pre>

I wish I can get multi lines code in my post also.
but in fact, all codes are placed in one line in my post.
<pre><code>int a = 10; int b = 10; int de = 10;</code></pre>

What should I do with html here ?

#### Technical details:

* sendgrid-nodejs Version: master (latest commit: [commit number])
* Node.js Version: 4.1.2

### PR DESCRIPTION
**Pull request by ssiddhantsharma**
# Fixes # 

Fixes #692

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
-  Made changes with several cases of <pre> tags to support line wrap.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=765) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=765) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=765) it.</sub>

**Comment by thinkingserious** [comment]
Hi @ssiddhantsharma,

Could you please move this content [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/TROUBLESHOOTING.md).

Thank you!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @ssiddhantsharma,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ssiddhantsharma** [comment]
@thinkingserious Updated the troubleshoot file with your request.
#785

**Comment by reedsa** [comment]
Thank you for the update! It looks like we can close this PR and move #785 forward.

**Comment by ssiddhantsharma** [comment]
@reedsa I am working on an updating #785, but yes we should close this one.

**Pull request closed without merging**
