### PR TITLE
Fixing travis build on master

### PR DESCRIPTION
**Pull request by nitish24p**
###Fixes travis build

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Travis is failing at the moment as it tries to run a test not described in package json
-  The tests are for those files which are not there on the system at the moment

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by nitish24p** [comment]
@adamreisnz

**Comment by adamreisnz** [comment]
@thinkingserious probably for you to have a look at, I never really dealt with the travis config

**Comment by nitish24p** [comment]
@adamreisnz The current config is trying to run a command which isnt defined in the scripts of package.json. Also the test is checking for some files which are not yet there in the master branch of the repo and hence they'd fail too.

**Comment by thinkingserious** [comment]
Hi @nitish24p,

This is on our backlog for review.

Thanks!

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Closing as the Travis build issues have been resolved elsewhere.

**Pull request closed without merging**
