### PR TITLE
Fix function name in mail helper and fix the corresponding test

### PR DESCRIPTION
**Pull request by seoker**
Per checked, no document or example is describing about the `bypass_management_list` under the `mailSetting` in Mail API, so I check the code and found the naming issue.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks @seoker!

Could you please take a moment to [sign our CLA](https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla) so we can review and merge your changes?

**Comment by seoker** [comment]
Hi,
I just signed it earlier today, I'm wondering how long should we wait until it gets approval?

**Comment by thinkingserious** [comment]
Hi @seoker,

Just saw the CLA and now we have added this fix to our backlog for review/merge. Thanks!

**Comment by thinkingserious** [comment]
Thanks again for the PR @seoker!

Please take a moment to fill out [this form]( https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so that we can send you some swag :)

**Pull request merged**
