### PR TITLE
Monorepo

### PR DESCRIPTION
**Pull request by adamreisnz**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @adamreisnz,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
How about I make a PR from this branch to master: https://github.com/sendgrid/sendgrid-nodejs/tree/monorepo and we can continue to collaborate there?

Eventually, we will move master to legacy or something similar.

**Comment by adamreisnz** [comment]
@thinkingserious yeah that should be fine. Do you want to create a new branch off master first with the current version?

**Comment by thinkingserious** [comment]
Do you think we need to? We are pretty much nuking the original master branch with respect to the monorepo branch.

**Comment by adamreisnz** [comment]
Yeah, but we need to probably keep that code base alive in case you want to maintain the 5.x version?

**Comment by adamreisnz** [comment]
Plus it has a lot of unit tests and documentation in there that will (at least parts of it) need to be ported to the new mono repo

**Comment by thinkingserious** [comment]
Ah yes, I was planning to make a legacy branch from master before we merge. I was going to wait to do that because we may have some updates between now and when we merge in monorepo.

**Comment by adamreisnz** [comment]
Ok sounds good. If you create the new PR, will I be able to push changes to that as well?

**Comment by thinkingserious** [comment]
Ah, damn. I can't add people outside of SendGrid to our repos. We'll need to work from your fork, but since I already merged it, I'm not sure if you need to create a new one. Sorry about that :(

**Comment by adamreisnz** [comment]
Ok yes, no worries, I'll pull in changes from your mono repo branch and
create a new PR for it into master of the sendgrid repo!



[image: photo]
Adam Reis
Co-founder at  Reis Ltd
M 022 100 1067 <+64+22+100+1067> E adam@reis.nz W www.reis.nz
<https://www.linkedin.com/in/adamreisnz> <http://twitter.com/adamreisnz>

**Comment by adamreisnz** [comment]
@thinkingserious I am pulling form the sendgrid/monorepo branch, but I noticed you renamed the @sendgrid/support package to @sendgrid/mail-helpers again. The helpers and classes in there are not just mail helpers, so I really wanted to give them more of a generic name.

If you dislike support, feel free to change it into something else, but I think it should reflect that it's not just mail helpers, but helpers that are used throughout the nodejs suite of packages.

**Comment by thinkingserious** [comment]
Hmm, I don't recall changing that. I think it was called mail-helpers in the project.json. In any case, I will respond in the other thread with my ideas.

**Pull request merged**
