### PR TITLE
Upgrade request to 2.88.0 (latest) to address issue #661

### LINKED ISSUE #661: @sendgrid/client dependency causes security risk
The bellow dependency chain introduces a security risk:

`@sendgrid/client@6.2.1 > request@2.83.0 > hawk@6.0.2 > hoek@4.2.0`

Detail: [https://nodesecurity.io/advisories/566](https://nodesecurity.io/advisories/566)

### PR DESCRIPTION
**Pull request by GuyKh**
# Fixes #661

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Upgrading request dependency to latest to fix inner dependency `request@2.83.0 > hawk@6.0.2 > hoek@4.2.0` vounrability

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=757) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=757) it.</sub>

**Comment by thinkingserious** [comment]
Hello @GuyKh,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by GuyKh** [comment]
@thinkingserious  - signed up.
Thanks! :)
I'd love to get some swag :) That's awesome!

**Comment by thinkingserious** [comment]
Awesome! Just be sure to accumulate enough points :) 

5 "difficulty: easy" or 2 "difficulty: medium" or 1 "difficulty: hard" or "difficulty: very hard".

Good luck!

**Comment by thinkingserious** [comment]
Hello @GuyKh,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @GuyKh,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Pull request merged**
