### PR TITLE
feat!: node version upgrade, axios upgrade

### PR DESCRIPTION
**Pull request by shrutiburman**
# Fixes #

This PR: 
Drops support for node v 6, 8, 10
### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/sendgrid/sendgrid-nodejs/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://support.sendgrid.com).

### CODE REVIEW

**Review by tiwarishubham635 — APPROVED** [review]

**Comment by tovbinm** [comment]
@tiwarishubham635 @manisha1997  can you please trigger a release for this version?

**Comment by jakebanks** [comment]
Is anyone else getting `axios3 is not a function` or similar since updating?

I patched Axios in one of our repos recently and discovered they'd updated the default export (see [comment](https://github.com/axios/axios/issues/5038#issuecomment-1270982590)).

So my imports changed from
```js
const axios = require('axios');
```

to
```js
const axios = require('axios').default;
```

Don't know enough about JS modules to understand if this change is also required here.

**Comment by Capta1nRaj** [comment]
Never till launch.

**Comment by Capta1nRaj** [comment]
> Is anyone else getting `axios3 is not a function` or similar when calling `send()` since updating? (i'm on 8.1.0)
> 
> I patched Axios in one of our repos recently and discovered they'd updated the default export (see [comment](https://github.com/axios/axios/issues/5038#issuecomment-1270982590)).
> 
> So my imports changed from
> 
> ```js
> const axios = require('axios');
> ```
> 
> to
> 
> ```js
> const axios = require('axios').default;
> ```
> 
> Don't know enough about JS modules to understand if this change is also required here.

Can you share your axios verion?

    "@sendgrid/mail": "^8.0.0",
    "axios": "^1.6.2",
    
    these are mine

**Comment by jakebanks** [comment]
> > Is anyone else getting `axios3 is not a function` or similar when calling `send()` since updating? (i'm on 8.1.0)
> > I patched Axios in one of our repos recently and discovered they'd updated the default export (see [comment](https://github.com/axios/axios/issues/5038#issuecomment-1270982590)).
> > So my imports changed from
> > ```js
> > const axios = require('axios');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```js
> > const axios = require('axios').default;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Don't know enough about JS modules to understand if this change is also required here.
> 
> Can you share your axios verion?
> 
> ```
> "@sendgrid/mail": "^8.0.0",
> "axios": "^1.6.2",
> 
> these are mine
> ```

Sure, I'm using

@sendgrid/mail at 8.1.0
axios 1.6.5

**Pull request merged**
