### PR TITLE
Repository overview sendgrid

### PR DESCRIPTION
**Pull request by nitish24p**
Fixes https://github.com/sendgrid/sendgrid-nodejs/issues/608

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
Makes an overview of the repo so that any new developer has a starting point. :)

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by nitish24p** [comment]
@thinkingserious  please have a look, is the format ok.
Also i have had a look at mail, client and helpers, need some more info on the mail parser , contact importer and the widget.

Regards
Nitish

**Comment by nitish24p** [comment]
@mbernier Your suggestions here would be great..

**Comment by thinkingserious** [comment]
Hello @nitish24p,

One of us will be reviewing once this comes up next in our backlog. We are processing PRs from oldest to newest currently.

We apologize for the delay and appreciate your patience.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @nitish24p,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
