### PR TITLE
Added how to deploy simple hello world app on Azure

### PR DESCRIPTION
**Pull request by SarasArya**
#467

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=490) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=490) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=490) it.</sub>

**Comment by thinkingserious** [comment]
Hi @SarasArya,

Could you please resolve the merge conflict? 

Thanks!

With Best Regards,

Elmer

**Comment by SarasArya** [comment]
Hi @clee rebased with master branch. Please merge

**Comment by SarasArya** [comment]
Hi whats the status on this?

**Comment by thinkingserious** [comment]
Hello @SarasArya,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
