### PR TITLE
Updated to use lodash 4

### PR DESCRIPTION
**Pull request by andrew-w-ross**
Corrected the file_handler to use Buffer.alloc when available.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @andrew-w-ross,

Thanks for the pull request!

I'm not sure if this dependency is now needed with the new library: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta and v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html (both come out of beta in a few weeks). 

If you do wish to contribute to the latest library, I'll need to make your pull request against the v3beta branch: https://github.com/sendgrid/sendgrid-nodejs/tree/v3beta and we will also need a signed CLA: https://github.com/sendgrid/sendgrid-nodejs/blob/v3beta/CONTRIBUTING.md#cla.

Thanks for your support,

Elmer

**Comment by andrew-w-ross** [comment]
@thinkingserious Unfortunately I'm going to be stuck on the current version for a while and those two changes I made are the things that are breaking my build on node 6.

**Comment by thinkingserious** [comment]
Thanks for the update @andrew-w-ross,

In that case, I suggest that you fork this repo, since as we move forward with the v3beta launch our resources will be focused there.

With Best Regards,

Elmer

**Comment by andrew-w-ross** [comment]
@thinkingserious I will thanks.

**Pull request closed without merging**
