### PR TITLE
Fix typing in mail.d.ts

### PR DESCRIPTION
**Pull request by tonyxiao**
Current
image

After
image

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=846) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=846) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=846) it.</sub>

**Comment by childish-sambino** [comment]
Duplicates #921

**Comment by dhritzkiv** [comment]
@tonyxiao sorry to steal your thunder with an exact duplicate of your PR (didn't see it when creating mine) 😛

**Comment by childish-sambino** [comment]
It's my fault as well. I don't go through PRs linearly so this happens occasionally. Plus there's a pretty large backlog.

**Pull request closed without merging**
