### PR TITLE
fix: Make various TypeScript request components optional

### PR DESCRIPTION
**Pull request by SPARTAN563**
This should address the issues faced in #353 while still ensuring that we accurately cover the type's requirements.

Please let me know if you have any concerns or further requests for this fix.

Regards,
Benjamin

/cc @sheyaweidberg

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @SPARTAN563,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by jpinkster** [comment]
ETA on merge?

**Comment by thinkingserious** [comment]
Hi @jpinkster,

I don't have a good ETA just yet, but I've added your vote to the issue to help it rise in our backlog.

Thanks!

**Comment by jpinkster** [comment]
🤘🏼

**Pull request merged**
