### PR TITLE
Decrease Cognitive Complexity in array-to-json.js

### PR DESCRIPTION
**Pull request by afischer12**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- This PR is to reduce the Cognitive Complexity (CC). I read up on CC and learned that && increases this number, so I removed the &&s in the if and used nested ifs instead. However, I also read that nesting increases the CC number. I do not know which one has more effect. Let me know what this update changed the CC to, and if it works, great. If not, we will try three && and combine it into a single conditional. If that doesn't work, then we'll see how we stand and I'll try something else.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=590) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=590) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=590) it.</sub>

**Comment by thinkingserious** [comment]
@afischer12

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by afischer12** [comment]
I've already filled out the form in another PR in another sendgrid project :)

**Comment by thinkingserious** [comment]
Thank you @afischer12, you are on the list!

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Three checks `&&`'d together as part of https://github.com/sendgrid/sendgrid-nodejs/pull/580. Considering this a duplicate.

**Pull request closed without merging**
