### PR TITLE
Add .codeclimate.yml for #557

### LINKED ISSUE #557: Add a .codeclimate.yml file to this repo
It is possible to configure how CodeClimate looks at a repository.
[These Docs](https://docs.codeclimate.com/docs/getting-started-configuration) explain how this is done. Please create an appropriate .codeclimate.yml for this repo. It should test the main language of the repo and run tests.

### PR DESCRIPTION
**Pull request by divyanshu013**
Hi guys, added and verified the codeclimate.yml configs. What do you suggest for running the tests?

@mbernier edit: closes #557

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=560) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=560) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=560) it.</sub>

**Comment by divyanshu013** [comment]
Sure @mbernier, there's an existing eslint config file [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/.eslintrc.yaml). Shall I add the missing fields from the mentioned PR's eslintrc.yml?

**Comment by mbernier** [comment]
Yeah, that would be awesome!

**Comment by divyanshu013** [comment]
Updated the config @mbernier, can you please check?

**Comment by mbernier** [comment]
This is great, thank you! 
I think I figured out that the unittests have to be added by us - so we are Good to go!

**Comment by thinkingserious** [comment]
Hello @divyanshu013,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by divyanshu013** [comment]
Awesome, thank you guys :smile_cat:

**Comment by divyanshu013** [comment]
Hey guys, I haven't received the swag or any notification for the same. I've filled the form in the above link again. Would be great if you can check. Thanks 🙂

**Comment by thinkingserious** [comment]
Hello @divyanshu013,

You are on our list to receive swag and I'll check with our provider on the status. 

I've noticed that, in general, shipments to India are taking much longer than other destinations. 

With Best Regards,

Elmer

**Pull request merged**
