### PR TITLE
Promise API and consistent callback function signature

### PR DESCRIPTION
**Pull request by adambuczynski**
This PR addresses the following issues:

- #240 
- #246 
- #206 

Notable changes:

- Extracted some logic into helpers
- Using a `getEmptyRequest` helper to avoid code duplication
- `emtpyRequest` now accepts an object with data to extend the empty request with, this will allow simpler syntax for initializing requests.
- Callback function now receives two parameters as per Node conventions (error, response)
- If no callback provided, the method will return a promise instead.
- Implemented promise API when not passing a callback function
- Using native Promise by default if present, but allow users to override this with any other implementation by setting `Sendgrid.Promise` to any value, e.g. `Sendgrid.Promise = require('bluebird')`

Example usage:

```js
let sendgrid = require('sendgrid');
sendgrid.SendGrid.Promise = require('bluebird');

let sg = sendgrid.SendGrid(process.env.SENDGRID_API_KEY);
let request = sg.emptyRequest({
  method: 'POST',
  path: '/v3/mail/send',
  body: mail.toJSON()
});

//Send request (returns promise)
sg.API(request)
  .then(response => ...)
  .catch(error => ...);

//Send request (using callback)
sg.API(request, (error, response) => {
  if (error) {
    //boo
  }
  //response always populated, even with error
});
```

### CODE REVIEW

**Comment by adambuczynski** [comment]
@thinkingserious can you check why the build is failing? I haven't made any API changes in this PR yet, so everything should still be working, yet all the tests seem to fail on an incorrect status code.

**Comment by thinkingserious** [comment]
Ah, since you are not part of the SendGrid repo, Travis is not loading the MOCK_HOST variable. I'll send instructions on how to create the test environment locally.

**Comment by adambuczynski** [comment]
Yes I figured that's why the tests would be failing locally, but on Travis it should still work, no?

**Comment by thinkingserious** [comment]
To test locally:

1. Install Prism: https://stoplight.io/prism
2. Run ./prism run --mock --list --spec https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai_stoplight.json

This will set up a mock local SendGrid server. When you run your tests locally they should pass.

For Node.js, we have have not automated this yet on Travis (it's coming), so it relies on their hosted server, whose unique URL is hidden behind the MOCK_HOST variable. Travis will only load that variable for those in the sengrid repo.

**Comment by adambuczynski** [comment]
Gotcha. I have added the changes to the API here. I might actually have to update the tests, as the callback now receives parameters in different order as per Node conventions.

Notable changes:
- Extracted some logic into helpers
- Use `getEmptyRequest` helper to avoid duplication
- Use native `Promise` by default if present, but allow users to override this with any other implementation
- Callback now receives two parameters as per Node conventions (error, response)
- If no callback provided, the method will return a promise instead.
- Removed unused ESLint plugins from package.json

**Comment by thinkingserious** [comment]
This is awesome!

Can you please allow us to send you some swag? Just email dx@sendgrid.com with a mailing address and T-shirt size.

**Comment by adambuczynski** [comment]
Sure will do, thanks :)

I've just pushed another commit which updates the tests and examples to use the new function signature. As this technically is a breaking change from the current version, you might want to release this under a new major version.

However, as it could also be considered a "fix" to adhere to Node standards, maybe you can get away with a minor release as well. But I'll leave that up to you :)

Let me know if there's anything else.

**Comment by adambuczynski** [comment]
Have run the tests locally with Prism and all pass 👍

**Comment by thinkingserious** [comment]
Awesome, love it!

I've gotten this into our backlog for review and merge.

Unfortunately, we have quite a few tickets in front of it, but this issue can move up our queue if others +1 or add comments.

**Comment by adambuczynski** [comment]
@thinkingserious I've updated the PR title and description to reflect what has changed. I think I might also remove the redundant `sendgrid.SendGrid` API, as it doesn't seem to add much value. The empty request that also gets exposed in the main `sendgrid` export is also accessible via the `sendgrid.SendGrid` function, so it seems a bit redundant.

Mind if we just export the main `SendGrid` function so one can do:

```js
let sendgrid = require('sendgrid');
let sg = sendgrid(process.env.SENDGRID_API_KEY);
```

Instead of the more verbose:

```js
let sendgrid = require('sendgrid');
sendgrid.SendGrid.Promise = require('bluebird');
let sg = sendgrid.SendGrid(process.env.SENDGRID_API_KEY);
```

**Comment by thinkingserious** [comment]
Beautiful and thanks again!

**Comment by adambuczynski** [comment]
Ok, done. I've also updated the `README.md` to reflect the new API.

**Comment by jamesdixon** [comment]
+1 LGTM

**Comment by thinkingserious** [comment]
@jamesdixon thanks for the vote, I've added your vote to help move this up the queue.

**Comment by liatreis** [comment]
+1

**Comment by thinkingserious** [comment]
@adambuczynski,

I'm now reviewing this pull request :)

So far, I've just tried to run the tests (`mocha`) and get the following error:

```bash
/Users/thinkingserious/Workspace/sendgrid/sendgrid-nodejs/lib/sendgrid.js:78
  this.API = function(request, callback) {
           ^

TypeError: Cannot set property 'API' of undefined
    at SendGrid (/Users/thinkingserious/Workspace/sendgrid/sendgrid-nodejs/lib/sendgrid.js:78:12)
    at Suite.<anonymous> (/Users/thinkingserious/Workspace/sendgrid/sendgrid-nodejs/test/test.js:13:12)
    at context.describe.context.context (/usr/local/lib/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Object.<anonymous> (/Users/thinkingserious/Workspace/sendgrid/sendgrid-nodejs/test/test.js:4:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by adambuczynski** [comment]
@thinkingserious interesting, I didn't make any changes to the architectural style of that core function, the `this` reference was always there:

https://github.com/sendgrid/sendgrid-nodejs/pull/261/files#diff-821a7fec86de51dd671e7622dc4cd6d9R78

Also, I didn't run into this error running the tests.

But I can refactor it to hide the `API` helper function altogether as a "private" method. Would you prefer that, or do you want to analyze the issue a bit further?

**Comment by thinkingserious** [comment]
@adambuczynski,

How did you run the tests?

**Comment by adambuczynski** [comment]
Via the way you suggested above. However, I tried again and have been able to reproduce it now as well. I think it's related to the way the `Sendgrid` function is exported now.

I have addressed this by referencing the `Sendgrid` function directly rather than using `this`, since the function is not meant to be called as a constructor with `new` anyway.

Tests are working and passing now.

**Comment by thinkingserious** [comment]
That did the trick :)

**Comment by adambuczynski** [comment]
Excellent, let me know if anything else comes up.

**Comment by adambuczynski** [comment]
Great, thanks for merging. How are you going to version these changes?

**Comment by thinkingserious** [comment]
I'm working on that right now. This will be a major version bump to 4.0. Should be done in about ~10 min.

**Comment by adambuczynski** [comment]
Ok sounds sensible.

Would you like to release it as a RC first and see if we can make other improvements that might be API breaking? That way we could include them without having to do another major release in the future.

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-nodejs/releases/tag/v4.0.0

**Comment by thinkingserious** [comment]
We don't currently have a RC workflow, but that sounds interesting. 

For now, we just make major version bumps when something breaks. We follow the semver.org convention.

**Comment by thinkingserious** [comment]
@adambuczynski oops, looks like we forget to remove the let's for var's. We have some breakage on the older node versions: https://travis-ci.org/sendgrid/sendgrid-nodejs/builds/149293172

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-nodejs/pull/264

**Comment by thinkingserious** [comment]
For Node v.10 looks like I need to catch this error: https://travis-ci.org/sendgrid/sendgrid-nodejs/jobs/149295924#L228

**Comment by adambuczynski** [comment]
Ok I'll have a look into these issues tomorrow. I am so used to using `let` that it's become a habit, and I never use `var` anymore, so they might have snuck in by accident ;)

**Comment by thinkingserious** [comment]
No worries, just about done fixing the issues :)

**Comment by adambuczynski** [comment]
Cool, as for the Promise error you can probably wrap that in an if statement to see if `Promise` is defined.

**Comment by thinkingserious** [comment]
Yes, the build is passing now :)

https://travis-ci.org/sendgrid/sendgrid-nodejs/builds/149298361

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-nodejs/releases/tag/v4.0.1

**Pull request merged**
