### PR TITLE
Convert response data to have valid json objects

### LINKED ISSUE #266: Response data should be valid json objects
#### Issue Summary

Currently, the data that you get from `SendgridError.response` is a stringified json. That means in order to inspect it you have to parse it with `JSON.parse`. Thats a pain in the ass to do. The same is true of the response body for successful calls. This leads to code like `const response = JSON.parse(response.body)` everywhere in order to actually use the result of API calls or `const body = JSON.parse(err.response.body)` in order to get the details from any errors.

I think it would make sense to parse this data in the library so that users of the library don't have to.

* sendgrid-nodejs Version: master
* Node.js Version: 4.1.2

### PR DESCRIPTION
**Pull request by hugoduraes**
Fixes #266

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @hugoduraes,

Thank you for your contribution!

Could you please take a moment and sign our CLA so we can review for merge? https://github.com/sendgrid/sendgrid-nodejs/blob/master/CONTRIBUTING.md#cla

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Wow, that was fast ;)

I just noticed you send the CLA in my next email. Thanks!

**Comment by hugoduraes** [comment]
I was going to reply that I had already signed and sent it! :)

**Comment by thinkingserious** [comment]
@hugoduraes,

Please take a moment to fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so that we can send you some swag :)

**Comment by hugoduraes** [comment]
Cool! :D

**Pull request merged**
