### PR TITLE
Bumped the moment, chai-as-promised, and dirty-chai version in package.json

### LINKED ISSUE #662: Repair potential security vulnerability - moment package
#### Issue Summary

Known moderate severity security vulnerability detected in moment < 2.19.3 defined in package-lock.json.
--
update suggested: moment ~> 2.19.3.

### PR DESCRIPTION
**Pull request by ctrimm**
# Fixes # 
Fixes #662.

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar) - *Done*
- [X] I have read the [Contribution Guide] and my PR follows them. - *Done*
- [X] I updated my branch with the master branch. - *Done*
- [X] I have added tests that prove my fix is effective or that my feature works - *No need for this*
- [X] I have added necessary documentation about the functionality in the appropriate .md file - *No need for this*
- [X] I have added in line documentation to the code I modified - *No need for this*

### Short description of what this PR does:
- This PR updates the version of moment in order to avoid the potential security vulnerability that exists in versions < 2.19.3
- While updating this dependency, I also had to update `chai-as-promised` and `dirty-chai`

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=666) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=666) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=666) it.</sub>

**Comment by thinkingserious** [comment]
Thanks @ctrimm! I've added this to our backlog for a code review and merge.

With Best Regards,

Elmer

**Comment by ctrimm** [comment]
Sounds good @thinkingserious. Feel free to let me know if you all catch anything I may have missed.

**Comment by ctrimm** [comment]
Just following back up on this @thinkingserious since it has been nearly 3 months.

**Comment by thinkingserious** [comment]
Thanks @ctrimm. This is still on our backlog and I don't have a firm date set for it's merge. I'm sorry I don't have a better answer :(

**Comment by ctrimm** [comment]
No worries @thinkingserious - just wanted to make sure it didn't get lost. 😄

**Comment by thinkingserious** [comment]
Hello @ctrimm,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
