### PR TITLE
Added setTimeout method to the MailService class

### LINKED ISSUE #894: Timeout implementation for @sendgrid/mail
I am using @sendgrid/mail in an AWS lambda function. For some reason, some of the requests do not receive a response within the max allowed execution time of the function (5s). This causes duplicate deliveries of the same mail (oops).

My solution would be to implement a timeout on the request itself which is < than the max allowed execution time of the function (to prevent retry).

Currently, the `@sendgrid/mail` package does not have a way a to set a timeout on @sendgrid/client. Fortunately, the `@sendgrid/client` class has a `setDefaultRequest` method which allows for a clean implementation of the timeout:

```
/**
 * Set client timeout
 */
setTimeout(timeout) {
  if (typeof timeout === 'undefined') {
    return;
  }

  this.client.setDefaultRequest('timeout', timeout);
}
```

Usage:

```
sgMail.setTimeout(6000);
```

This would change the `timeout` option in https://github.com/request/request#requestoptions-callback:

`Time to wait for a server to send response headers (and start the response body) before aborting the request. `

I'm happy to make a PR if this is acceptable.

### PR DESCRIPTION
**Pull request by peterkuiper**
Fixes #894 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the development branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:

This PR adds a setTimeout method to the MailService class. It uses the `setDefaultRequest` method of `@sendgrid/client`. This allows
you to change the timeout option in https://github.com/request/request#requestoptions-callback.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=898) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-nodejs?pullRequest=898) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-nodejs?pullRequest=898) it.</sub>

**Comment by peterkuiper** [comment]
Not sure how to add a test for this as it is only adding an option which is used directly by the `request` module.

**Comment by wizardofauz** [comment]
Any plans on getting this merged any time soon?

**Comment by peterkuiper** [comment]
Merge conflicts have been fixed, it seems the documentation got rearranged :)

**Comment by thinkingserious** [comment]
Hello @peterkuiper,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
