### PR TITLE
chore: fixed axios vulnerability

### PR DESCRIPTION
**Pull request by tiwarishubham635**
# Fixes #

Axios version has been updated to 1.6.4 to fix [this vulnerability](https://security.snyk.io/package/npm/axios/1.6.0)

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/sendgrid/sendgrid-nodejs/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://support.sendgrid.com).

### CODE REVIEW

**Comment by tiwarishubham635** [comment]
We also need to update the client version in mail [here](https://github.com/sendgrid/sendgrid-nodejs/blob/main/packages/mail/package.json#L30)

**Review by shrutiburman — APPROVED** [review]

**Comment by tiwarishubham635** [comment]
> We also need to update the client version in mail [here](https://github.com/sendgrid/sendgrid-nodejs/blob/main/packages/mail/package.json#L30)

Actually, it is not needed manually. The release will do it automatically like [this](https://github.com/sendgrid/sendgrid-nodejs/commit/2d4d51214d63961d3138421c297790b479c12c26#diff-8c3909060d423b030efb146102ed856391aabb2a3eca58422b9f28a28af616edR30)

**Comment by jakebanks** [comment]
Looks like this change hasn't been deployed

**Comment by suhrob008** [comment]
image
Who knows why this is giving an error?

**Comment by suhrob008** [comment]
who knows?

**Comment by suhrob008** [comment]
> image Who knows why this is giving an error?

who knows?

**Comment by suhrob008** [comment]
> > image Who knows why this is giving an error?
>

**Comment by suhrob008** [comment]
who knows?

**Pull request merged**
